-- Cities directory + service-area coverage on businesses.

-- ---------------------------------------------------------------------------
-- cities table
-- ---------------------------------------------------------------------------
create table if not exists public.cities (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name text not null,
  county text not null,
  region text not null,
  population int,
  is_featured boolean not null default false,
  intro_html text,
  created_at timestamptz not null default now()
);

comment on table public.cities is 'Florida municipalities + major CDPs used for service-area selection and city/category landing pages.';

create index if not exists cities_region_idx on public.cities (region);
create index if not exists cities_featured_idx on public.cities (is_featured) where is_featured = true;
create index if not exists cities_population_idx on public.cities (population desc nulls last);

alter table public.cities enable row level security;

create policy "Cities are viewable by everyone"
  on public.cities for select
  to anon, authenticated
  using (true);

-- ---------------------------------------------------------------------------
-- businesses: service-area coverage
-- ---------------------------------------------------------------------------
alter table public.businesses
  add column if not exists service_areas text[] not null default '{}',
  add column if not exists serves_statewide boolean not null default false;

create index if not exists businesses_service_areas_idx
  on public.businesses using gin (service_areas);

create index if not exists businesses_serves_statewide_idx
  on public.businesses (serves_statewide)
  where serves_statewide = true;

-- ---------------------------------------------------------------------------
-- Seed FL cities (incorporated municipalities + major CDPs)
-- region values: panhandle | north-central | northeast | central | tampa-bay
--                | southwest | treasure-coast | south | keys
-- ---------------------------------------------------------------------------
insert into public.cities (slug, name, county, region, population, is_featured) values
  -- South Florida — Miami-Dade
  ('miami', 'Miami', 'Miami-Dade', 'south', 442241, true),
  ('hialeah', 'Hialeah', 'Miami-Dade', 'south', 223109, true),
  ('miami-gardens', 'Miami Gardens', 'Miami-Dade', 'south', 111640, true),
  ('miami-beach', 'Miami Beach', 'Miami-Dade', 'south', 82890, true),
  ('homestead', 'Homestead', 'Miami-Dade', 'south', 80737, false),
  ('north-miami', 'North Miami', 'Miami-Dade', 'south', 60191, false),
  ('coral-gables', 'Coral Gables', 'Miami-Dade', 'south', 49248, false),
  ('doral', 'Doral', 'Miami-Dade', 'south', 78813, true),
  ('aventura', 'Aventura', 'Miami-Dade', 'south', 40071, false),
  ('cutler-bay', 'Cutler Bay', 'Miami-Dade', 'south', 45527, false),
  ('palmetto-bay', 'Palmetto Bay', 'Miami-Dade', 'south', 24793, false),
  ('pinecrest', 'Pinecrest', 'Miami-Dade', 'south', 19400, false),
  ('kendall', 'Kendall', 'Miami-Dade', 'south', 80238, false),
  ('miami-lakes', 'Miami Lakes', 'Miami-Dade', 'south', 31339, false),
  ('north-miami-beach', 'North Miami Beach', 'Miami-Dade', 'south', 43881, false),
  ('opa-locka', 'Opa-locka', 'Miami-Dade', 'south', 16463, false),
  ('south-miami', 'South Miami', 'Miami-Dade', 'south', 12108, false),
  ('sweetwater', 'Sweetwater', 'Miami-Dade', 'south', 21413, false),
  ('hialeah-gardens', 'Hialeah Gardens', 'Miami-Dade', 'south', 23054, false),
  ('miami-springs', 'Miami Springs', 'Miami-Dade', 'south', 13859, false),
  ('miami-shores', 'Miami Shores', 'Miami-Dade', 'south', 10493, false),
  ('key-biscayne', 'Key Biscayne', 'Miami-Dade', 'south', 14809, false),
  ('sunny-isles-beach', 'Sunny Isles Beach', 'Miami-Dade', 'south', 22219, false),
  ('surfside', 'Surfside', 'Miami-Dade', 'south', 5683, false),
  ('bal-harbour', 'Bal Harbour', 'Miami-Dade', 'south', 3023, false),
  ('bay-harbor-islands', 'Bay Harbor Islands', 'Miami-Dade', 'south', 5839, false),
  ('florida-city', 'Florida City', 'Miami-Dade', 'south', 12442, false),
  ('north-bay-village', 'North Bay Village', 'Miami-Dade', 'south', 8159, false),
  ('biscayne-park', 'Biscayne Park', 'Miami-Dade', 'south', 3199, false),
  ('el-portal', 'El Portal', 'Miami-Dade', 'south', 2325, false),
  ('golden-beach', 'Golden Beach', 'Miami-Dade', 'south', 950, false),
  ('indian-creek', 'Indian Creek', 'Miami-Dade', 'south', 42, false),
  ('medley', 'Medley', 'Miami-Dade', 'south', 1085, false),
  ('virginia-gardens', 'Virginia Gardens', 'Miami-Dade', 'south', 2380, false),
  ('west-miami', 'West Miami', 'Miami-Dade', 'south', 7174, false),

  -- South Florida — Broward
  ('fort-lauderdale', 'Fort Lauderdale', 'Broward', 'south', 184255, true),
  ('pembroke-pines', 'Pembroke Pines', 'Broward', 'south', 171178, true),
  ('hollywood', 'Hollywood', 'Broward', 'south', 153067, true),
  ('miramar', 'Miramar', 'Broward', 'south', 134721, true),
  ('coral-springs', 'Coral Springs', 'Broward', 'south', 134394, true),
  ('pompano-beach', 'Pompano Beach', 'Broward', 'south', 112046, true),
  ('davie', 'Davie', 'Broward', 'south', 105691, true),
  ('plantation', 'Plantation', 'Broward', 'south', 91750, true),
  ('sunrise', 'Sunrise', 'Broward', 'south', 97335, true),
  ('lauderhill', 'Lauderhill', 'Broward', 'south', 74482, false),
  ('weston', 'Weston', 'Broward', 'south', 68107, false),
  ('tamarac', 'Tamarac', 'Broward', 'south', 71897, false),
  ('margate', 'Margate', 'Broward', 'south', 58796, false),
  ('coconut-creek', 'Coconut Creek', 'Broward', 'south', 57833, false),
  ('deerfield-beach', 'Deerfield Beach', 'Broward', 'south', 86859, false),
  ('oakland-park', 'Oakland Park', 'Broward', 'south', 44229, false),
  ('hallandale-beach', 'Hallandale Beach', 'Broward', 'south', 39417, false),
  ('north-lauderdale', 'North Lauderdale', 'Broward', 'south', 44794, false),
  ('cooper-city', 'Cooper City', 'Broward', 'south', 36482, false),
  ('parkland', 'Parkland', 'Broward', 'south', 36359, false),
  ('dania-beach', 'Dania Beach', 'Broward', 'south', 31723, false),
  ('wilton-manors', 'Wilton Manors', 'Broward', 'south', 12551, false),
  ('lauderdale-by-the-sea', 'Lauderdale-by-the-Sea', 'Broward', 'south', 6056, false),
  ('lighthouse-point', 'Lighthouse Point', 'Broward', 'south', 10979, false),
  ('pembroke-park', 'Pembroke Park', 'Broward', 'south', 6101, false),
  ('west-park', 'West Park', 'Broward', 'south', 14951, false),
  ('southwest-ranches', 'Southwest Ranches', 'Broward', 'south', 7589, false),
  ('hillsboro-beach', 'Hillsboro Beach', 'Broward', 'south', 1845, false),
  ('sea-ranch-lakes', 'Sea Ranch Lakes', 'Broward', 'south', 670, false),

  -- South Florida — Palm Beach
  ('west-palm-beach', 'West Palm Beach', 'Palm Beach', 'south', 117415, true),
  ('boca-raton', 'Boca Raton', 'Palm Beach', 'south', 97422, true),
  ('boynton-beach', 'Boynton Beach', 'Palm Beach', 'south', 80380, true),
  ('delray-beach', 'Delray Beach', 'Palm Beach', 'south', 66846, true),
  ('wellington', 'Wellington', 'Palm Beach', 'south', 61637, false),
  ('jupiter', 'Jupiter', 'Palm Beach', 'south', 61047, true),
  ('palm-beach-gardens', 'Palm Beach Gardens', 'Palm Beach', 'south', 59182, true),
  ('royal-palm-beach', 'Royal Palm Beach', 'Palm Beach', 'south', 38967, false),
  ('greenacres', 'Greenacres', 'Palm Beach', 'south', 43990, false),
  ('lake-worth-beach', 'Lake Worth Beach', 'Palm Beach', 'south', 42219, false),
  ('riviera-beach', 'Riviera Beach', 'Palm Beach', 'south', 37604, false),
  ('palm-springs', 'Palm Springs', 'Palm Beach', 'south', 26890, false),
  ('lantana', 'Lantana', 'Palm Beach', 'south', 11504, false),
  ('belle-glade', 'Belle Glade', 'Palm Beach', 'south', 17042, false),
  ('pahokee', 'Pahokee', 'Palm Beach', 'south', 5731, false),
  ('tequesta', 'Tequesta', 'Palm Beach', 'south', 6244, false),
  ('juno-beach', 'Juno Beach', 'Palm Beach', 'south', 3580, false),
  ('north-palm-beach', 'North Palm Beach', 'Palm Beach', 'south', 13139, false),
  ('palm-beach', 'Palm Beach', 'Palm Beach', 'south', 9245, false),
  ('lake-park', 'Lake Park', 'Palm Beach', 'south', 8624, false),
  ('atlantis', 'Atlantis', 'Palm Beach', 'south', 2192, false),
  ('manalapan', 'Manalapan', 'Palm Beach', 'south', 462, false),
  ('south-palm-beach', 'South Palm Beach', 'Palm Beach', 'south', 1431, false),
  ('hypoluxo', 'Hypoluxo', 'Palm Beach', 'south', 2697, false),
  ('briny-breezes', 'Briny Breezes', 'Palm Beach', 'south', 410, false),
  ('ocean-ridge', 'Ocean Ridge', 'Palm Beach', 'south', 1928, false),
  ('highland-beach', 'Highland Beach', 'Palm Beach', 'south', 4295, false),
  ('gulf-stream', 'Gulf Stream', 'Palm Beach', 'south', 1115, false),
  ('golf', 'Golf', 'Palm Beach', 'south', 252, false),
  ('haverhill', 'Haverhill', 'Palm Beach', 'south', 2114, false),
  ('mangonia-park', 'Mangonia Park', 'Palm Beach', 'south', 1888, false),
  ('loxahatchee-groves', 'Loxahatchee Groves', 'Palm Beach', 'south', 3438, false),
  ('westlake', 'Westlake', 'Palm Beach', 'south', 1335, false),

  -- Florida Keys — Monroe
  ('key-west', 'Key West', 'Monroe', 'keys', 26444, true),
  ('marathon', 'Marathon', 'Monroe', 'keys', 8779, false),
  ('islamorada', 'Islamorada', 'Monroe', 'keys', 6293, false),
  ('key-largo', 'Key Largo', 'Monroe', 'keys', 9909, false),
  ('tavernier', 'Tavernier', 'Monroe', 'keys', 2299, false),
  ('big-pine-key', 'Big Pine Key', 'Monroe', 'keys', 5172, false),
  ('layton', 'Layton', 'Monroe', 'keys', 195, false),

  -- Treasure Coast
  ('port-st-lucie', 'Port St. Lucie', 'St. Lucie', 'treasure-coast', 231790, true),
  ('fort-pierce', 'Fort Pierce', 'St. Lucie', 'treasure-coast', 47297, false),
  ('vero-beach', 'Vero Beach', 'Indian River', 'treasure-coast', 16354, false),
  ('sebastian', 'Sebastian', 'Indian River', 'treasure-coast', 25054, false),
  ('fellsmere', 'Fellsmere', 'Indian River', 'treasure-coast', 5612, false),
  ('stuart', 'Stuart', 'Martin', 'treasure-coast', 17946, false),
  ('jensen-beach', 'Jensen Beach', 'Martin', 'treasure-coast', 12648, false),
  ('hobe-sound', 'Hobe Sound', 'Martin', 'treasure-coast', 14037, false),
  ('palm-city', 'Palm City', 'Martin', 'treasure-coast', 25085, false),
  ('indiantown', 'Indiantown', 'Martin', 'treasure-coast', 6094, false),
  ('sewalls-point', 'Sewall''s Point', 'Martin', 'treasure-coast', 2014, false),
  ('jupiter-island', 'Jupiter Island', 'Martin', 'treasure-coast', 819, false),
  ('okeechobee', 'Okeechobee', 'Okeechobee', 'treasure-coast', 5573, false),

  -- Space Coast (Brevard)
  ('palm-bay', 'Palm Bay', 'Brevard', 'central', 119760, true),
  ('melbourne', 'Melbourne', 'Brevard', 'central', 84678, true),
  ('titusville', 'Titusville', 'Brevard', 'central', 48789, false),
  ('cocoa', 'Cocoa', 'Brevard', 'central', 19729, false),
  ('cocoa-beach', 'Cocoa Beach', 'Brevard', 'central', 11341, false),
  ('rockledge', 'Rockledge', 'Brevard', 'central', 28287, false),
  ('satellite-beach', 'Satellite Beach', 'Brevard', 'central', 11451, false),
  ('west-melbourne', 'West Melbourne', 'Brevard', 'central', 25278, false),
  ('indian-harbour-beach', 'Indian Harbour Beach', 'Brevard', 'central', 8417, false),
  ('cape-canaveral', 'Cape Canaveral', 'Brevard', 'central', 10193, false),
  ('indialantic', 'Indialantic', 'Brevard', 'central', 2913, false),
  ('melbourne-beach', 'Melbourne Beach', 'Brevard', 'central', 3127, false),
  ('palm-shores', 'Palm Shores', 'Brevard', 'central', 1115, false),
  ('malabar', 'Malabar', 'Brevard', 'central', 3035, false),
  ('grant-valkaria', 'Grant-Valkaria', 'Brevard', 'central', 4326, false),

  -- Central Florida — Orange, Seminole, Osceola, Lake, Sumter
  ('orlando', 'Orlando', 'Orange', 'central', 307573, true),
  ('apopka', 'Apopka', 'Orange', 'central', 56295, false),
  ('winter-park', 'Winter Park', 'Orange', 'central', 29795, false),
  ('ocoee', 'Ocoee', 'Orange', 'central', 47795, false),
  ('winter-garden', 'Winter Garden', 'Orange', 'central', 46964, false),
  ('maitland', 'Maitland', 'Orange', 'central', 19543, false),
  ('belle-isle', 'Belle Isle', 'Orange', 'central', 7045, false),
  ('edgewood', 'Edgewood', 'Orange', 'central', 2935, false),
  ('eatonville', 'Eatonville', 'Orange', 'central', 2155, false),
  ('oakland', 'Oakland', 'Orange', 'central', 3473, false),
  ('windermere', 'Windermere', 'Orange', 'central', 3447, false),
  ('sanford', 'Sanford', 'Seminole', 'central', 61051, false),
  ('altamonte-springs', 'Altamonte Springs', 'Seminole', 'central', 46197, false),
  ('oviedo', 'Oviedo', 'Seminole', 'central', 41486, false),
  ('longwood', 'Longwood', 'Seminole', 'central', 15776, false),
  ('casselberry', 'Casselberry', 'Seminole', 'central', 28387, false),
  ('lake-mary', 'Lake Mary', 'Seminole', 'central', 17142, false),
  ('winter-springs', 'Winter Springs', 'Seminole', 'central', 38223, false),
  ('kissimmee', 'Kissimmee', 'Osceola', 'central', 79226, true),
  ('st-cloud', 'St. Cloud', 'Osceola', 'central', 60110, false),
  ('celebration', 'Celebration', 'Osceola', 'central', 11296, false),
  ('buenaventura-lakes', 'Buenaventura Lakes', 'Osceola', 'central', 33172, false),
  ('poinciana', 'Poinciana', 'Osceola/Polk', 'central', 71874, false),
  ('clermont', 'Clermont', 'Lake', 'central', 44316, false),
  ('eustis', 'Eustis', 'Lake', 'central', 22573, false),
  ('tavares', 'Tavares', 'Lake', 'central', 19000, false),
  ('mount-dora', 'Mount Dora', 'Lake', 'central', 16341, false),
  ('leesburg', 'Leesburg', 'Lake', 'central', 27948, false),
  ('minneola', 'Minneola', 'Lake', 'central', 14091, false),
  ('groveland', 'Groveland', 'Lake', 'central', 19457, false),
  ('lady-lake', 'Lady Lake', 'Lake', 'central', 16832, false),
  ('howey-in-the-hills', 'Howey-in-the-Hills', 'Lake', 'central', 1500, false),
  ('mascotte', 'Mascotte', 'Lake', 'central', 6306, false),
  ('montverde', 'Montverde', 'Lake', 'central', 1715, false),
  ('umatilla', 'Umatilla', 'Lake', 'central', 3993, false),
  ('astatula', 'Astatula', 'Lake', 'central', 2199, false),
  ('the-villages', 'The Villages', 'Sumter', 'central', 79077, false),
  ('bushnell', 'Bushnell', 'Sumter', 'central', 3082, false),
  ('wildwood', 'Wildwood', 'Sumter', 'central', 16383, false),
  ('coleman', 'Coleman', 'Sumter', 'central', 678, false),
  ('webster', 'Webster', 'Sumter', 'central', 906, false),
  ('center-hill', 'Center Hill', 'Sumter', 'central', 1051, false),

  -- Central Florida — Volusia, Flagler, Polk
  ('daytona-beach', 'Daytona Beach', 'Volusia', 'central', 72647, true),
  ('deltona', 'Deltona', 'Volusia', 'central', 93692, false),
  ('port-orange', 'Port Orange', 'Volusia', 'central', 62203, false),
  ('ormond-beach', 'Ormond Beach', 'Volusia', 'central', 43080, false),
  ('deland', 'DeLand', 'Volusia', 'central', 37351, false),
  ('new-smyrna-beach', 'New Smyrna Beach', 'Volusia', 'central', 30142, false),
  ('edgewater', 'Edgewater', 'Volusia', 'central', 24033, false),
  ('south-daytona', 'South Daytona', 'Volusia', 'central', 13177, false),
  ('holly-hill', 'Holly Hill', 'Volusia', 'central', 12576, false),
  ('debary', 'DeBary', 'Volusia', 'central', 21343, false),
  ('orange-city', 'Orange City', 'Volusia', 'central', 13066, false),
  ('lake-helen', 'Lake Helen', 'Volusia', 'central', 2782, false),
  ('oak-hill', 'Oak Hill', 'Volusia', 'central', 2110, false),
  ('daytona-beach-shores', 'Daytona Beach Shores', 'Volusia', 'central', 4391, false),
  ('ponce-inlet', 'Ponce Inlet', 'Volusia', 'central', 3243, false),
  ('pierson', 'Pierson', 'Volusia', 'central', 1717, false),
  ('palm-coast', 'Palm Coast', 'Flagler', 'northeast', 95553, false),
  ('flagler-beach', 'Flagler Beach', 'Flagler', 'northeast', 5160, false),
  ('bunnell', 'Bunnell', 'Flagler', 'northeast', 3276, false),
  ('beverly-beach', 'Beverly Beach', 'Flagler', 'northeast', 416, false),
  ('lakeland', 'Lakeland', 'Polk', 'central', 112641, true),
  ('winter-haven', 'Winter Haven', 'Polk', 'central', 50118, false),
  ('bartow', 'Bartow', 'Polk', 'central', 19960, false),
  ('auburndale', 'Auburndale', 'Polk', 'central', 17839, false),
  ('haines-city', 'Haines City', 'Polk', 'central', 32554, false),
  ('lake-wales', 'Lake Wales', 'Polk', 'central', 16962, false),
  ('mulberry', 'Mulberry', 'Polk', 'central', 4123, false),
  ('davenport', 'Davenport', 'Polk', 'central', 8783, false),
  ('polk-city', 'Polk City', 'Polk', 'central', 2425, false),
  ('lake-alfred', 'Lake Alfred', 'Polk', 'central', 6080, false),
  ('fort-meade', 'Fort Meade', 'Polk', 'central', 5736, false),
  ('frostproof', 'Frostproof', 'Polk', 'central', 2982, false),
  ('dundee', 'Dundee', 'Polk', 'central', 5009, false),
  ('eagle-lake', 'Eagle Lake', 'Polk', 'central', 3014, false),
  ('lake-hamilton', 'Lake Hamilton', 'Polk', 'central', 1490, false),

  -- Tampa Bay — Hillsborough
  ('tampa', 'Tampa', 'Hillsborough', 'tampa-bay', 384959, true),
  ('plant-city', 'Plant City', 'Hillsborough', 'tampa-bay', 41695, false),
  ('temple-terrace', 'Temple Terrace', 'Hillsborough', 'tampa-bay', 26690, false),
  ('brandon', 'Brandon', 'Hillsborough', 'tampa-bay', 114626, false),
  ('riverview', 'Riverview', 'Hillsborough', 'tampa-bay', 110704, false),
  ('valrico', 'Valrico', 'Hillsborough', 'tampa-bay', 41685, false),
  ('lutz', 'Lutz', 'Hillsborough', 'tampa-bay', 22790, false),
  ('citrus-park', 'Citrus Park', 'Hillsborough', 'tampa-bay', 27894, false),
  ('westchase', 'Westchase', 'Hillsborough', 'tampa-bay', 25600, false),
  ('carrollwood', 'Carrollwood', 'Hillsborough', 'tampa-bay', 39378, false),
  ('town-n-country', 'Town ''n'' Country', 'Hillsborough', 'tampa-bay', 87543, false),
  ('apollo-beach', 'Apollo Beach', 'Hillsborough', 'tampa-bay', 23618, false),
  ('sun-city-center', 'Sun City Center', 'Hillsborough', 'tampa-bay', 30068, false),
  ('wimauma', 'Wimauma', 'Hillsborough', 'tampa-bay', 11136, false),

  -- Tampa Bay — Pinellas
  ('st-petersburg', 'St. Petersburg', 'Pinellas', 'tampa-bay', 261254, true),
  ('clearwater', 'Clearwater', 'Pinellas', 'tampa-bay', 117292, true),
  ('largo', 'Largo', 'Pinellas', 'tampa-bay', 84948, false),
  ('pinellas-park', 'Pinellas Park', 'Pinellas', 'tampa-bay', 53093, false),
  ('dunedin', 'Dunedin', 'Pinellas', 'tampa-bay', 36420, false),
  ('tarpon-springs', 'Tarpon Springs', 'Pinellas', 'tampa-bay', 26167, false),
  ('seminole', 'Seminole', 'Pinellas', 'tampa-bay', 19134, false),
  ('safety-harbor', 'Safety Harbor', 'Pinellas', 'tampa-bay', 17072, false),
  ('oldsmar', 'Oldsmar', 'Pinellas', 'tampa-bay', 15052, false),
  ('south-pasadena', 'South Pasadena', 'Pinellas', 'tampa-bay', 5316, false),
  ('madeira-beach', 'Madeira Beach', 'Pinellas', 'tampa-bay', 4263, false),
  ('treasure-island', 'Treasure Island', 'Pinellas', 'tampa-bay', 6845, false),
  ('st-pete-beach', 'St. Pete Beach', 'Pinellas', 'tampa-bay', 9244, false),
  ('indian-rocks-beach', 'Indian Rocks Beach', 'Pinellas', 'tampa-bay', 4071, false),
  ('indian-shores', 'Indian Shores', 'Pinellas', 'tampa-bay', 1380, false),
  ('redington-beach', 'Redington Beach', 'Pinellas', 'tampa-bay', 1421, false),
  ('redington-shores', 'Redington Shores', 'Pinellas', 'tampa-bay', 2118, false),
  ('north-redington-beach', 'North Redington Beach', 'Pinellas', 'tampa-bay', 1454, false),
  ('belleair', 'Belleair', 'Pinellas', 'tampa-bay', 4145, false),
  ('belleair-beach', 'Belleair Beach', 'Pinellas', 'tampa-bay', 1543, false),
  ('belleair-bluffs', 'Belleair Bluffs', 'Pinellas', 'tampa-bay', 2289, false),
  ('kenneth-city', 'Kenneth City', 'Pinellas', 'tampa-bay', 4965, false),
  ('gulfport', 'Gulfport', 'Pinellas', 'tampa-bay', 12608, false),

  -- Tampa Bay — Pasco, Hernando
  ('new-port-richey', 'New Port Richey', 'Pasco', 'tampa-bay', 16728, false),
  ('port-richey', 'Port Richey', 'Pasco', 'tampa-bay', 2884, false),
  ('zephyrhills', 'Zephyrhills', 'Pasco', 'tampa-bay', 17194, false),
  ('dade-city', 'Dade City', 'Pasco', 'tampa-bay', 7838, false),
  ('san-antonio', 'San Antonio', 'Pasco', 'tampa-bay', 1283, false),
  ('st-leo', 'St. Leo', 'Pasco', 'tampa-bay', 1284, false),
  ('wesley-chapel', 'Wesley Chapel', 'Pasco', 'tampa-bay', 64866, false),
  ('land-o-lakes', 'Land O'' Lakes', 'Pasco', 'tampa-bay', 38416, false),
  ('trinity', 'Trinity', 'Pasco', 'tampa-bay', 13141, false),
  ('hudson', 'Hudson', 'Pasco', 'tampa-bay', 12158, false),
  ('holiday', 'Holiday', 'Pasco', 'tampa-bay', 23475, false),
  ('brooksville', 'Brooksville', 'Hernando', 'tampa-bay', 7711, false),
  ('weeki-wachee', 'Weeki Wachee', 'Hernando', 'tampa-bay', 16, false),
  ('spring-hill', 'Spring Hill', 'Hernando', 'tampa-bay', 113568, false),

  -- Southwest Florida — Lee, Collier, Charlotte, Sarasota, Manatee
  ('cape-coral', 'Cape Coral', 'Lee', 'southwest', 224455, true),
  ('fort-myers', 'Fort Myers', 'Lee', 'southwest', 92245, true),
  ('bonita-springs', 'Bonita Springs', 'Lee', 'southwest', 53644, false),
  ('estero', 'Estero', 'Lee', 'southwest', 35831, false),
  ('sanibel', 'Sanibel', 'Lee', 'southwest', 6469, false),
  ('fort-myers-beach', 'Fort Myers Beach', 'Lee', 'southwest', 5582, false),
  ('lehigh-acres', 'Lehigh Acres', 'Lee', 'southwest', 124551, false),
  ('north-fort-myers', 'North Fort Myers', 'Lee', 'southwest', 42376, false),
  ('naples', 'Naples', 'Collier', 'southwest', 19115, true),
  ('marco-island', 'Marco Island', 'Collier', 'southwest', 16413, false),
  ('everglades-city', 'Everglades City', 'Collier', 'southwest', 357, false),
  ('golden-gate', 'Golden Gate', 'Collier', 'southwest', 23961, false),
  ('immokalee', 'Immokalee', 'Collier', 'southwest', 24557, false),
  ('punta-gorda', 'Punta Gorda', 'Charlotte', 'southwest', 19471, false),
  ('port-charlotte', 'Port Charlotte', 'Charlotte', 'southwest', 60090, false),
  ('sarasota', 'Sarasota', 'Sarasota', 'southwest', 54842, true),
  ('north-port', 'North Port', 'Sarasota', 'southwest', 80021, false),
  ('venice', 'Venice', 'Sarasota', 'southwest', 25463, false),
  ('longboat-key', 'Longboat Key', 'Sarasota/Manatee', 'southwest', 7327, false),
  ('englewood', 'Englewood', 'Sarasota/Charlotte', 'southwest', 16196, false),
  ('bradenton', 'Bradenton', 'Manatee', 'southwest', 55698, true),
  ('palmetto', 'Palmetto', 'Manatee', 'southwest', 13371, false),
  ('bradenton-beach', 'Bradenton Beach', 'Manatee', 'southwest', 989, false),
  ('anna-maria', 'Anna Maria', 'Manatee', 'southwest', 803, false),
  ('holmes-beach', 'Holmes Beach', 'Manatee', 'southwest', 3925, false),
  ('lakewood-ranch', 'Lakewood Ranch', 'Manatee/Sarasota', 'southwest', 64863, false),

  -- Heartland
  ('sebring', 'Sebring', 'Highlands', 'central', 10491, false),
  ('avon-park', 'Avon Park', 'Highlands', 'central', 10146, false),
  ('lake-placid', 'Lake Placid', 'Highlands', 'central', 2300, false),
  ('wauchula', 'Wauchula', 'Hardee', 'central', 5051, false),
  ('bowling-green', 'Bowling Green', 'Hardee', 'central', 2902, false),
  ('zolfo-springs', 'Zolfo Springs', 'Hardee', 'central', 1893, false),
  ('moore-haven', 'Moore Haven', 'Glades', 'central', 1739, false),
  ('labelle', 'LaBelle', 'Hendry', 'central', 5079, false),
  ('clewiston', 'Clewiston', 'Hendry', 'central', 7457, false),

  -- North Central Florida
  ('gainesville', 'Gainesville', 'Alachua', 'north-central', 141085, true),
  ('alachua', 'Alachua', 'Alachua', 'north-central', 10678, false),
  ('newberry', 'Newberry', 'Alachua', 'north-central', 7307, false),
  ('high-springs', 'High Springs', 'Alachua', 'north-central', 6215, false),
  ('archer', 'Archer', 'Alachua', 'north-central', 1118, false),
  ('hawthorne', 'Hawthorne', 'Alachua', 'north-central', 1416, false),
  ('micanopy', 'Micanopy', 'Alachua', 'north-central', 612, false),
  ('waldo', 'Waldo', 'Alachua', 'north-central', 1117, false),
  ('ocala', 'Ocala', 'Marion', 'north-central', 64304, true),
  ('belleview', 'Belleview', 'Marion', 'north-central', 5104, false),
  ('dunnellon', 'Dunnellon', 'Marion', 'north-central', 1830, false),
  ('silver-springs-shores', 'Silver Springs Shores', 'Marion', 'north-central', 23552, false),
  ('crystal-river', 'Crystal River', 'Citrus', 'north-central', 3461, false),
  ('inverness', 'Inverness', 'Citrus', 'north-central', 7475, false),
  ('beverly-hills', 'Beverly Hills', 'Citrus', 'north-central', 8341, false),
  ('homosassa-springs', 'Homosassa Springs', 'Citrus', 'north-central', 14283, false),
  ('chiefland', 'Chiefland', 'Levy', 'north-central', 2402, false),
  ('williston', 'Williston', 'Levy', 'north-central', 2768, false),
  ('cedar-key', 'Cedar Key', 'Levy', 'north-central', 723, false),
  ('bronson', 'Bronson', 'Levy', 'north-central', 1101, false),
  ('inglis', 'Inglis', 'Levy', 'north-central', 1325, false),
  ('trenton', 'Trenton', 'Gilchrist', 'north-central', 2049, false),
  ('bell', 'Bell', 'Gilchrist', 'north-central', 470, false),
  ('cross-city', 'Cross City', 'Dixie', 'north-central', 1659, false),
  ('palatka', 'Palatka', 'Putnam', 'north-central', 10561, false),
  ('crescent-city', 'Crescent City', 'Putnam', 'north-central', 1490, false),
  ('interlachen', 'Interlachen', 'Putnam', 'north-central', 1404, false),
  ('starke', 'Starke', 'Bradford', 'north-central', 5447, false),
  ('lake-butler', 'Lake Butler', 'Union', 'north-central', 1885, false),
  ('lake-city', 'Lake City', 'Columbia', 'north-central', 12329, false),
  ('fort-white', 'Fort White', 'Columbia', 'north-central', 638, false),
  ('jasper', 'Jasper', 'Hamilton', 'north-central', 4546, false),
  ('jennings', 'Jennings', 'Hamilton', 'north-central', 824, false),
  ('white-springs', 'White Springs', 'Hamilton', 'north-central', 705, false),
  ('live-oak', 'Live Oak', 'Suwannee', 'north-central', 6900, false),
  ('branford', 'Branford', 'Suwannee', 'north-central', 743, false),
  ('mayo', 'Mayo', 'Lafayette', 'north-central', 1153, false),
  ('madison', 'Madison', 'Madison', 'north-central', 2873, false),
  ('greenville', 'Greenville', 'Madison', 'north-central', 815, false),
  ('monticello', 'Monticello', 'Jefferson', 'north-central', 2207, false),
  ('perry', 'Perry', 'Taylor', 'north-central', 6884, false),
  ('fanning-springs', 'Fanning Springs', 'Levy/Gilchrist', 'north-central', 794, false),

  -- Northeast Florida — Duval, Nassau, St. Johns, Clay, Baker
  ('jacksonville', 'Jacksonville', 'Duval', 'northeast', 949611, true),
  ('jacksonville-beach', 'Jacksonville Beach', 'Duval', 'northeast', 23830, false),
  ('atlantic-beach', 'Atlantic Beach', 'Duval', 'northeast', 13783, false),
  ('neptune-beach', 'Neptune Beach', 'Duval', 'northeast', 7174, false),
  ('baldwin', 'Baldwin', 'Duval', 'northeast', 1410, false),
  ('fernandina-beach', 'Fernandina Beach', 'Nassau', 'northeast', 13345, false),
  ('callahan', 'Callahan', 'Nassau', 'northeast', 1335, false),
  ('hilliard', 'Hilliard', 'Nassau', 'northeast', 3257, false),
  ('st-augustine', 'St. Augustine', 'St. Johns', 'northeast', 15065, false),
  ('st-augustine-beach', 'St. Augustine Beach', 'St. Johns', 'northeast', 7146, false),
  ('orange-park', 'Orange Park', 'Clay', 'northeast', 8412, false),
  ('green-cove-springs', 'Green Cove Springs', 'Clay', 'northeast', 11367, false),
  ('keystone-heights', 'Keystone Heights', 'Clay', 'northeast', 1349, false),
  ('middleburg', 'Middleburg', 'Clay', 'northeast', 14096, false),
  ('penney-farms', 'Penney Farms', 'Clay', 'northeast', 813, false),
  ('macclenny', 'Macclenny', 'Baker', 'northeast', 6829, false),
  ('glen-st-mary', 'Glen St. Mary', 'Baker', 'northeast', 444, false),

  -- Panhandle — Leon, Wakulla, Gadsden, Franklin, Calhoun, Jackson, Holmes, Washington
  ('tallahassee', 'Tallahassee', 'Leon', 'panhandle', 201731, true),
  ('crawfordville', 'Crawfordville', 'Wakulla', 'panhandle', 5266, false),
  ('quincy', 'Quincy', 'Gadsden', 'panhandle', 7972, false),
  ('chattahoochee', 'Chattahoochee', 'Gadsden', 'panhandle', 3327, false),
  ('havana', 'Havana', 'Gadsden', 'panhandle', 1808, false),
  ('midway', 'Midway', 'Gadsden', 'panhandle', 3210, false),
  ('greensboro', 'Greensboro', 'Gadsden', 'panhandle', 599, false),
  ('gretna', 'Gretna', 'Gadsden', 'panhandle', 1500, false),
  ('bristol', 'Bristol', 'Liberty', 'panhandle', 996, false),
  ('apalachicola', 'Apalachicola', 'Franklin', 'panhandle', 2245, false),
  ('carrabelle', 'Carrabelle', 'Franklin', 'panhandle', 2767, false),
  ('blountstown', 'Blountstown', 'Calhoun', 'panhandle', 2273, false),
  ('altha', 'Altha', 'Calhoun', 'panhandle', 506, false),
  ('marianna', 'Marianna', 'Jackson', 'panhandle', 7468, false),
  ('graceville', 'Graceville', 'Jackson', 'panhandle', 2284, false),
  ('sneads', 'Sneads', 'Jackson', 'panhandle', 1858, false),
  ('cottondale', 'Cottondale', 'Jackson', 'panhandle', 1029, false),
  ('bonifay', 'Bonifay', 'Holmes', 'panhandle', 2776, false),
  ('chipley', 'Chipley', 'Washington', 'panhandle', 3478, false),
  ('vernon', 'Vernon', 'Washington', 'panhandle', 717, false),

  -- Panhandle — Bay, Gulf, Walton, Okaloosa, Santa Rosa, Escambia
  ('panama-city', 'Panama City', 'Bay', 'panhandle', 32083, false),
  ('panama-city-beach', 'Panama City Beach', 'Bay', 'panhandle', 17780, false),
  ('lynn-haven', 'Lynn Haven', 'Bay', 'panhandle', 21770, false),
  ('callaway', 'Callaway', 'Bay', 'panhandle', 14405, false),
  ('springfield', 'Springfield', 'Bay', 'panhandle', 9098, false),
  ('parker', 'Parker', 'Bay', 'panhandle', 4185, false),
  ('mexico-beach', 'Mexico Beach', 'Bay', 'panhandle', 1072, false),
  ('port-st-joe', 'Port St. Joe', 'Gulf', 'panhandle', 3543, false),
  ('wewahitchka', 'Wewahitchka', 'Gulf', 'panhandle', 1908, false),
  ('defuniak-springs', 'DeFuniak Springs', 'Walton', 'panhandle', 6841, false),
  ('freeport', 'Freeport', 'Walton', 'panhandle', 2747, false),
  ('paxton', 'Paxton', 'Walton', 'panhandle', 692, false),
  ('santa-rosa-beach', 'Santa Rosa Beach', 'Walton', 'panhandle', 5523, false),
  ('miramar-beach', 'Miramar Beach', 'Walton', 'panhandle', 8519, false),
  ('inlet-beach', 'Inlet Beach', 'Walton', 'panhandle', 1751, false),
  ('fort-walton-beach', 'Fort Walton Beach', 'Okaloosa', 'panhandle', 22515, false),
  ('crestview', 'Crestview', 'Okaloosa', 'panhandle', 27134, false),
  ('destin', 'Destin', 'Okaloosa', 'panhandle', 14315, false),
  ('niceville', 'Niceville', 'Okaloosa', 'panhandle', 16121, false),
  ('mary-esther', 'Mary Esther', 'Okaloosa', 'panhandle', 4067, false),
  ('valparaiso', 'Valparaiso', 'Okaloosa', 'panhandle', 5067, false),
  ('shalimar', 'Shalimar', 'Okaloosa', 'panhandle', 707, false),
  ('cinco-bayou', 'Cinco Bayou', 'Okaloosa', 'panhandle', 449, false),
  ('laurel-hill', 'Laurel Hill', 'Okaloosa', 'panhandle', 484, false),
  ('milton', 'Milton', 'Santa Rosa', 'panhandle', 11045, false),
  ('gulf-breeze', 'Gulf Breeze', 'Santa Rosa', 'panhandle', 6648, false),
  ('jay', 'Jay', 'Santa Rosa', 'panhandle', 600, false),
  ('pensacola', 'Pensacola', 'Escambia', 'panhandle', 54312, true),
  ('century', 'Century', 'Escambia', 'panhandle', 1697, false)
on conflict (slug) do nothing;
